In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
sns.set()

In [17]:
!dir

 Volume in drive D has no label.
 Volume Serial Number is 3417-05D0

 Directory of d:\PythonTraining\Codexa\PyTorch

2020/06/27  11:37    <DIR>          .
2020/06/27  11:37    <DIR>          ..
2020/06/27  11:23    <DIR>          .ipynb_checkpoints
2020/06/27  11:23           158,316 datasets_9366_13206_ramen-ratings.csv
2020/06/27  11:37            18,804 ramen ratings.ipynb
               2 File(s)        177,120 bytes
               3 Dir(s)  961,257,771,008 bytes free


In [18]:
ramen = pd.read_csv('datasets_9366_13206_ramen-ratings.csv')
ramen

Review #           Brand  \
0         2580       New Touch   
1         2579        Just Way   
2         2578          Nissin   
3         2577         Wei Lih   
4         2576  Ching's Secret   
...        ...             ...   
2575         5           Vifon   
2576         4         Wai Wai   
2577         3         Wai Wai   
2578         2         Wai Wai   
2579         1        Westbrae   

                                                Variety Style   Country Stars  \
0                             T's Restaurant Tantanmen    Cup     Japan  3.75   
1     Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...  Pack    Taiwan     1   
2                         Cup Noodles Chicken Vegetable   Cup       USA  2.25   
3                         GGE Ramen Snack Tomato Flavor  Pack    Taiwan  2.75   
4                                       Singapore Curry  Pack     India  3.75   
...                                                 ...   ...       ...   ...   
2575  Hu Tiu Nam Vang ["Phnom Penh" style] Asian Sty...  Bowl   Vietnam   3.5   
2576                     Oriental Style Instant Noodles  Pack  Thailand     1   
2577                                     Tom Yum Shrimp  Pack  Thailand     2   
2578                               Tom Yum Chili Flavor  Pack  Thailand     2   
2579                                         Miso Ramen  Pack       USA   0.5   

     Top Ten  
0        NaN  
1        NaN  
2        NaN  
3        NaN  
4        NaN  
...      ...  
2575     NaN  
2576     NaN  
2577     NaN  
2578     NaN  
2579     NaN  

[2580 rows x 7 columns]

In [19]:
ramen.describe(include='all')

Review #   Brand  Variety Style Country Stars Top Ten
count   2580.000000    2580     2580  2578    2580  2580      41
unique          NaN     355     2413     7      38    51      38
top             NaN  Nissin  Chicken  Pack   Japan     4      \n
freq            NaN     381        7  1531     352   384       4
mean    1290.500000     NaN      NaN   NaN     NaN   NaN     NaN
std      744.926171     NaN      NaN   NaN     NaN   NaN     NaN
min        1.000000     NaN      NaN   NaN     NaN   NaN     NaN
25%      645.750000     NaN      NaN   NaN     NaN   NaN     NaN
50%     1290.500000     NaN      NaN   NaN     NaN   NaN     NaN
75%     1935.250000     NaN      NaN   NaN     NaN   NaN     NaN
max     2580.000000     NaN      NaN   NaN     NaN   NaN     NaN

In [20]:
import torch
import torch.nn as nn

from sklearn.metrics import mean_squared_error as mse

In [21]:
ramen.shape

(2580, 7)

In [22]:
ramen.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2580 entries, 0 to 2579
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Review #  2580 non-null   int64 
 1   Brand     2580 non-null   object
 2   Variety   2580 non-null   object
 3   Style     2578 non-null   object
 4   Country   2580 non-null   object
 5   Stars     2580 non-null   object
 6   Top Ten   41 non-null     object
dtypes: int64(1), object(6)
memory usage: 141.2+ KB


In [23]:
ramen['Country'].value_counts()

Japan            352
USA              323
South Korea      309
Taiwan           224
Thailand         191
China            169
Malaysia         156
Hong Kong        137
Indonesia        126
Singapore        109
Vietnam          108
UK                69
Philippines       47
Canada            41
India             31
Germany           27
Mexico            25
Australia         22
Netherlands       15
Nepal             14
Myanmar           14
Hungary            9
Pakistan           9
Bangladesh         7
Colombia           6
Cambodia           5
Brazil             5
Holland            4
Poland             4
Fiji               4
Finland            3
Sweden             3
Sarawak            3
Dubai              3
Estonia            2
Ghana              2
Nigeria            1
United States      1
Name: Country, dtype: int64

In [24]:
ramen['Stars'].value_counts()

4          384
5          369
3.75       350
3.5        326
3          173
3.25       170
4.25       143
4.5        132
2.75        85
2           68
2.5         67
4.75        64
1.5         37
1.75        27
0           26
1           26
2.25        21
0.5         14
0.25        11
1.25        10
5.0         10
3.50         9
5.00         7
4.00         6
4.3          4
3.8          3
4.50         3
4.0          3
Unrated      3
2.9          2
2.8          2
3.0          2
4.125        2
1.1          2
2.3          2
3.1          2
3.3          1
3.6          1
2.125        1
3.65         1
0.9          1
3.4          1
2.85         1
0.75         1
0.1          1
3.125        1
3.00         1
3.2          1
3.7          1
1.8          1
2.1          1
Name: Stars, dtype: int64

In [29]:
mask = ramen.index[ramen['Stars'] == 'Unrated']
ramen = ramen.drop(index = mask)
ramen.shape

(2577, 7)

In [30]:
print(ramen['Stars'].dtype)

object


In [31]:
ramen['Stars'] = ramen['Stars'].astype(float)

In [32]:
print(ramen['Stars'].dtype)

float64


In [33]:
ramen = ramen.drop(columns=['Review #', 'Top Ten', 'Variety'])
ramen.head()

Brand Style Country  Stars
0       New Touch   Cup   Japan   3.75
1        Just Way  Pack  Taiwan   1.00
2          Nissin   Cup     USA   2.25
3         Wei Lih  Pack  Taiwan   2.75
4  Ching's Secret  Pack   India   3.75

In [35]:
Country = pd.get_dummies(ramen['Country'], prefix=['Country'], drop_first=True)
Brand = pd.get_dummies(ramen['Brand'], prefix='Brand', drop_first=True)
Style = pd.get_dummies(ramen['Style'], prefix='Style', drop_first=True)

In [37]:
ramendf = pd.concat([Country, Brand, Style], axis=1)
ramendf

['Country']_Bangladesh  ['Country']_Brazil  ['Country']_Cambodia  \
0                          0                   0                     0   
1                          0                   0                     0   
2                          0                   0                     0   
3                          0                   0                     0   
4                          0                   0                     0   
...                      ...                 ...                   ...   
2575                       0                   0                     0   
2576                       0                   0                     0   
2577                       0                   0                     0   
2578                       0                   0                     0   
2579                       0                   0                     0   

      ['Country']_Canada  ['Country']_China  ['Country']_Colombia  \
0                      0                  0                     0   
1                      0                  0                     0   
2                      0                  0                     0   
3                      0                  0                     0   
4                      0                  0                     0   
...                  ...                ...                   ...   
2575                   0                  0                     0   
2576                   0                  0                     0   
2577                   0                  0                     0   
2578                   0                  0                     0   
2579                   0                  0                     0   

      ['Country']_Dubai  ['Country']_Estonia  ['Country']_Fiji  \
0                     0                    0                 0   
1                     0                    0                 0   
2                     0                    0                 0   
3                     0                    0                 0   
4                     0                    0                 0   
...                 ...                  ...               ...   
2575                  0                    0                 0   
2576                  0                    0                 0   
2577                  0                    0                 0   
2578                  0                    0                 0   
2579                  0                    0                 0   

      ['Country']_Finland  ...  Brand_Yum-Mie  Brand_Zow Zow  Brand_iMee  \
0                       0  ...              0              0           0   
1                       0  ...              0              0           0   
2                       0  ...              0              0           0   
3                       0  ...              0              0           0   
4                       0  ...              0              0           0   
...                   ...  ...            ...            ...         ...   
2575                    0  ...              0              0           0   
2576                    0  ...              0              0           0   
2577                    0  ...              0              0           0   
2578                    0  ...              0              0           0   
2579                    0  ...              0              0           0   

      Brand_iNoodle  Style_Bowl  Style_Box  Style_Can  Style_Cup  Style_Pack  \
0                 0           0          0          0          1           0   
1                 0           0          0          0          0           1   
2                 0           0          0          0          1           0   
3                 0           0          0          0          0           1   
4                 0           0          0          0          0           1   
...             ...         ...        ...        ...        ...         ...   
2575              0   

In [38]:
X = np.array(ramendf, dtype=np.float32)
y = np.array(ramen[['Stars']], dtype=np.float32)

In [39]:
# Linear Regression
model = nn.Linear(397, 1)

In [40]:
X

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [42]:
y

array([[3.75],
       [1.  ],
       [2.25],
       ...,
       [2.  ],
       [2.  ],
       [0.5 ]], dtype=float32)

In [43]:
# 損失関数
loss = nn.MSELoss()

# 最適化関数
optimizer = torch.optim.SGD(model.parameters(), lr=0.6)

In [44]:
# training Model
for epoch in range(1000):
    # stage1 numpy to tensor
    inputs = torch.from_numpy(X)
    targets = torch.from_numpy(y)
    
    # stage2 calculate costs
    outputs = model(inputs)
    cost = loss(outputs, targets)
    
    # stage3 backward
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # stage4 output logs
    if (epoch+1) % 100 == 0:
        print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, 1000, cost.item()))


Epoch [100/1000], Loss: 0.7757
Epoch [200/1000], Loss: 0.7273
Epoch [300/1000], Loss: 0.6985
Epoch [400/1000], Loss: 0.6787
Epoch [500/1000], Loss: 0.6639
Epoch [600/1000], Loss: 0.6524
Epoch [700/1000], Loss: 0.6431
Epoch [800/1000], Loss: 0.6353
Epoch [900/1000], Loss: 0.6288
Epoch [1000/1000], Loss: 0.6232


In [45]:
# output predict
y_pred = model(torch.from_numpy(X)).data.numpy()

In [46]:
print(y_pred[0:5])
print(y[0:5])

[[4.11076  ]
 [2.9528368]
 [3.4566958]
 [3.4206345]
 [3.7058773]]
[[3.75]
 [1.  ]
 [2.25]
 [2.75]
 [3.75]]


In [49]:
# 平均二乗誤差を確認
mse(y, y_pred)

0.6231158